# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 319d75b710a3dd987e0bcd3c36288c03d80646eb1a6b3328fd9b0b8da6626e8f9e330b595b376b02b3b51701a59e8f71e060d301d6e4f439be3849e0be2b2f38

test:
  secret_key_base: 8e0312cbc364a4ad3ded8ca7aa0570cc77b7ddbe64f9300b83d0e41449ed52cbbcc11ce8d42bb6fdca9ba102443491e7cc92ceac28021be2fe88b74b5900fe2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
